/**
 * price-oracle-agent.ts — v0.0.0.2
 *
 * Fetches the live BTC and ETH prices via a real **Somnia Agent** call —
 * not a plain HTTP request. The agent (JSON API Request, agent id below)
 * fetches CoinGecko itself, several independent validator nodes execute it,
 * they reach consensus on the result, and only the consensus value lands
 * on-chain. That's the whole point of this step: the price estimate we'll
 * compare against DreamDEX's implied probability (from v0.0.0.3 onward) is
 * verifiable on-chain, not a number our own backend just claims to have
 * fetched.
 *
 * Unlike v0.0.0.1 (pure read), THIS version WRITES to the chain — every
 * agent invocation is a transaction (`createRequest`), so it needs a
 * **funded testnet wallet**:
 *
 *   1. Generate a fresh throwaway wallet — NEVER reuse a real wallet here.
 *   2. Get free STT from the Somnia testnet faucet.
 *   3. Put the private key in .env as PRIVATE_KEY (never commit .env —
 *      it's already in .gitignore).
 *
 * Cost: still zero dollars. STT is free testnet gas, and the "deposit"
 * an agent call requires is paid in STT too (partly refunded — see
 * `docs.somnia.network/agents/invoking-agents/from-solidity` for the
 * fund-flow). Nothing here touches real money on any network.
 *
 * The integration code below (createRequest / status-polling flow) started
 * from the exact TypeScript snippet Somnia's own Agent Explorer
 * (https://agents.testnet.somnia.network/agent/13174292974160097713,
 * "TypeScript" tab), which is generated directly from the deployed
 * contract's ABI. It was then generalized into a reusable function and
 * type-checked against viem's real types (see CHANGES.md).
 *
 * Run:
 *   npm install
 *   npm run price-agent
 */

import "dotenv/config";
import {
  createPublicClient,
  createWalletClient,
  http,
  fallback,
  encodeFunctionData,
  decodeFunctionResult,
  decodeEventLog,
  type Hex,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { somniaShannon } from "@somnia-chain/markets-sdk/chains";

// --- Config -------------------------------------------------------------
// Defaults are the values generated by the official Agent Explorer for this
// agent, on Somnia Shannon Testnet (chain 50312) — the same network
// v0.0.0.1 already uses for DreamDEX. All free/testnet, zero cost.
// Real-world testnet RPCs go down or block requests sometimes — confirmed
// live during development: dream-rpc.somnia.network returned a hard 403 for
// a while. Rather than hardcode one URL and hope, we list several official
// candidates and let viem's `fallback` transport automatically move to the
// next one if the current one errors, with no manual .env editing needed.
// Override with a comma-separated list via SOMNIA_AGENT_RPC_URLS if needed.
const RPC_URLS = (
  process.env.SOMNIA_AGENT_RPC_URLS ??
  "https://dream-rpc.somnia.network/,https://api.infra.testnet.somnia.network/"
)
  .split(",")
  .map((u) => u.trim())
  .filter(Boolean);
const PLATFORM_ADDRESS = (process.env.SOMNIA_AGENTS_CONTRACT ??
  "0x037Bb9C718F3f7fe5eCBDB0b600D607b52706776") as Hex;

// The "JSON API Request" base agent. Verify this still resolves at
// https://agents.testnet.somnia.network if requests start failing —
// like DreamDEX's venueId (see v0.0.0.1), agent ids are platform data,
// not something to assume is permanent.
const JSON_API_REQUEST_AGENT_ID = 13174292974160097713n;

// From the generated snippet's comments: "matches the platform default".
// Used only to size a safe deposit; the contract itself is the source of
// truth (we still read the live floor via getRequestDeposit() below).
const PER_AGENT_EXECUTION_COST = 30_000_000_000_000_000n; // 0.03 STT
const SUBCOMMITTEE_SIZE = 3n;

// Live testing showed typical finalization in well under 2 seconds — this
// is a generous safety-margin ceiling, not the expected wait time.
const REQUEST_TIMEOUT_MS = 60 * 1000;

// Platform ABI (subset of IAgentRequester — from the generated snippet).
const platformAbi = [
  {
    type: "function",
    name: "createRequest",
    inputs: [
      { type: "uint256", name: "agentId" },
      { type: "address", name: "callbackAddress" },
      { type: "bytes4", name: "callbackSelector" },
      { type: "bytes", name: "payload" },
    ],
    outputs: [{ type: "uint256", name: "requestId" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getRequestDeposit",
    inputs: [],
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "RequestCreated",
    inputs: [
      { type: "uint256", name: "requestId", indexed: true },
      { type: "uint256", name: "agentId", indexed: true },
      { type: "uint256", name: "perAgentBudget", indexed: false },
      { type: "bytes", name: "payload", indexed: false },
      { type: "address[]", name: "subcommittee", indexed: false },
    ],
  },
] as const;

// fetchUint's own ABI — used to both encode our call and decode the result.
const fetchUintAbi = [
  {
    type: "function",
    name: "fetchUint",
    inputs: [
      { type: "string", name: "url" },
      { type: "string", name: "selector" },
      { type: "uint8", name: "decimals" },
    ],
    outputs: [{ type: "uint256", name: "result" }],
  },
] as const;

// CoinGecko's free, keyless "simple price" endpoint. One request covers
// both assets; each on-chain agent call below just points at a different
// dot-notation selector within the same JSON body.
const COINGECKO_URL =
  process.env.COINGECKO_URL_PRICES ??
  "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd";

// 8 decimals matches the official docs example and gives plenty of
// precision for a USD price while staying an integer on-chain.
const PRICE_DECIMALS = 8;

const ASSETS = [
  { label: "BTC", selector: "bitcoin.usd" },
  { label: "ETH", selector: "ethereum.usd" },
] as const;

const RECEIPTS_SERVICE_URL =
  process.env.SOMNIA_RECEIPTS_SERVICE_URL ?? "https://receipts.testnet.agents.somnia.host";

type MinimalReceipt = {
  status: "success" | "failed" | "timeout";
  errorMessage?: string;
  // The ABI-encoded return value lives here. `response` (also present on a
  // receipt) is metadata about the agent's own outbound HTTP call
  // (e.g. `{ status: 200, size: 32 }`) — NOT the contract return value.
  agentReceipt?: { result: Hex };
};

type MinimalReceiptsResponse = {
  count: number;
  receipts: MinimalReceipt[];
};

async function fetchPriceViaAgent(
  publicClient: ReturnType<typeof createPublicClient>,
  walletClient: ReturnType<typeof createWalletClient>,
  selector: string
): Promise<bigint> {
  const payload = encodeFunctionData({
    abi: fetchUintAbi,
    functionName: "fetchUint",
    args: [COINGECKO_URL, selector, PRICE_DECIMALS],
  });

  // Safe deposit: contract floor + per-agent execution reward. Floor alone
  // would be accepted by the contract, but runners skip requests whose
  // perAgentBudget is below their scheduled execution cost.
  const reserve = await publicClient.readContract({
    address: PLATFORM_ADDRESS,
    abi: platformAbi,
    functionName: "getRequestDeposit",
  });
  const reward = PER_AGENT_EXECUTION_COST * SUBCOMMITTEE_SIZE;
  const deposit = reserve + reward;

  const hash = await walletClient.writeContract({
    address: PLATFORM_ADDRESS,
    abi: platformAbi,
    functionName: "createRequest",
    args: [
      JSON_API_REQUEST_AGENT_ID,
      "0x0000000000000000000000000000000000000000", // no callback — we read the result via the Receipts Service instead
      "0x00000000",
      payload,
    ],
    value: deposit,
    chain: somniaShannon,
    account: walletClient.account!,
  });

  console.log(`   tx: ${hash} — waiting for confirmation...`);
  const receipt = await publicClient.waitForTransactionReceipt({ hash });

  const createdLog = receipt.logs.find((log) => {
    try {
      const decoded = decodeEventLog({ abi: platformAbi, data: log.data, topics: log.topics });
      return decoded.eventName === "RequestCreated";
    } catch {
      return false;
    }
  });
  if (!createdLog) throw new Error("RequestCreated event not found in transaction logs");
  const decodedCreated = decodeEventLog({
    abi: platformAbi,
    data: createdLog.data,
    topics: createdLog.topics,
  });
  if (decodedCreated.eventName !== "RequestCreated") {
    throw new Error("Unexpected event decoded where RequestCreated was expected");
  }
  const requestId = decodedCreated.args.requestId;
  console.log(`   requestId: ${requestId} — polling the Receipts Service for consensus...`);

  // IMPORTANT: this does NOT poll getRequest() on the platform contract.
  // Real testing found on-chain request data gets pruned (deleted, for gas
  // refunds) essentially as soon as a request finalizes — getRequest()
  // reverts with a decoded `RequestNotFound(uint256)` custom error once
  // that happens, often before our very first poll. The official Receipts
  // Service (docs.somnia.network/agents/invoking-agents/receipts) is
  // exactly the intended way to read a result after the fact — it's backed
  // by durable off-chain storage, not the pruned on-chain struct.
  const pollIntervalMs = 1000;
  const maxConsecutiveErrors = 5;
  const deadline = Date.now() + REQUEST_TIMEOUT_MS;
  const receiptsUrl = `${RECEIPTS_SERVICE_URL}/agent-receipts?contractAddress=${PLATFORM_ADDRESS}&requestId=${requestId}&type=minimal`;

  const successReceipt = await (async () => {
    let consecutiveErrors = 0;
    for (;;) {
      try {
        const res = await fetch(receiptsUrl);
        if (!res.ok) {
          throw new Error(`Receipts Service HTTP ${res.status}`);
        }
        const data = (await res.json()) as MinimalReceiptsResponse;
        consecutiveErrors = 0;

        const successOne = data.receipts?.find((r) => r.status === "success");
        if (successOne) return successOne;

        // Not every validator succeeding isn't necessarily fatal — only
        // treat this as a real failure once enough validators have reported
        // in and NONE of them succeeded (mirrors the on-chain threshold of
        // 2-of-3 rather than bailing on the first straggler).
        const reported = data.receipts ?? [];
        if (reported.length >= 2 && reported.every((r) => r.status !== "success")) {
          const first = reported[0];
          throw new Error(
            first.status === "failed"
              ? `Agent execution failed: ${first.errorMessage ?? "no error message"}`
              : "Request timed out (per receipt)"
          );
        }
        // Otherwise: still pending (0/1 receipts in, or not enough info yet) — keep polling.
      } catch (err) {
        // A receipt with status "failed"/"timeout" is a real, final result —
        // don't retry those. Only retry on network/HTTP-layer errors.
        if (err instanceof Error && err.message.startsWith("Agent execution")) throw err;
        if (err instanceof Error && err.message.startsWith("Request timed out")) throw err;

        consecutiveErrors++;
        if (consecutiveErrors > maxConsecutiveErrors) {
          throw new Error(
            `Receipts Service failed ${maxConsecutiveErrors} times in a row: ${
              err instanceof Error ? err.message : err
            }`
          );
        }
        console.log(
          `   ⚠️  Receipts Service call failed (attempt ${consecutiveErrors}/${maxConsecutiveErrors}), retrying...`
        );
      }
      if (Date.now() > deadline) {
        throw new Error(`Timed out polling the Receipts Service after ${REQUEST_TIMEOUT_MS / 1000}s`);
      }
      await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));
    }
  })();

  if (!successReceipt.agentReceipt?.result) {
    throw new Error("Receipt reported success but carried no agentReceipt.result");
  }

  const result = decodeFunctionResult({
    abi: fetchUintAbi,
    functionName: "fetchUint",
    data: successReceipt.agentReceipt.result,
  });

  // Runtime guard, not just a type-level assumption: if the agent's ABI
  // ever changes shape, fail loudly here rather than silently miscomputing
  // a price downstream.
  if (typeof result !== "bigint") {
    throw new Error(`Unexpected decoded result type from fetchUint: ${typeof result}`);
  }

  return result;
}

async function main() {
  console.log("\n🤖 Somnia Agent — on-chain BTC/ETH price fetch (testnet)\n");

  const privateKey = process.env.PRIVATE_KEY;
  if (!privateKey) {
    console.error("❌ PRIVATE_KEY is not set in .env.");
    console.error(
      "   This version writes to the chain, so it needs a funded testnet wallet.\n" +
        "   Generate a fresh throwaway key, fund it from the Somnia testnet faucet, and set PRIVATE_KEY in .env.\n" +
        "   Never use a real/mainnet wallet's key here.\n"
    );
    process.exit(1);
  }

  const account = privateKeyToAccount(privateKey as Hex);
  console.log(`Using wallet: ${account.address}`);
  console.log(`RPC fallback chain: ${RPC_URLS.join(" -> ")}\n`);

  // fallback() tries transports in order and automatically moves to the
  // next one on error (bad response, timeout, non-2xx, etc.) — this is what
  // actually saves us from a single dead RPC without any manual switching.
  const transport = fallback(RPC_URLS.map((url) => http(url)));
  const publicClient = createPublicClient({ chain: somniaShannon, transport });
  const walletClient = createWalletClient({ account, chain: somniaShannon, transport });

  const results: { label: string; usd: number }[] = [];

  for (const asset of ASSETS) {
    console.log(`Requesting ${asset.label} price via Somnia Agent (JSON API Request)...`);
    try {
      const raw = await fetchPriceViaAgent(publicClient, walletClient, asset.selector);
      const usd = Number(raw) / 10 ** PRICE_DECIMALS;
      console.log(`   ✅ ${asset.label} = $${usd.toLocaleString(undefined, { maximumFractionDigits: 2 })}\n`);
      results.push({ label: asset.label, usd });
    } catch (err) {
      console.error(`   ❌ Failed to fetch ${asset.label} price:`, err instanceof Error ? err.message : err);
      console.log("");
    }
  }

  if (results.length === 0) {
    console.log("No prices were fetched successfully. See errors above.\n");
    process.exit(1);
  }

  console.table(results.map((r) => ({ Asset: r.label, "Price (USD)": r.usd })));
  console.log(
    `\n✅ Fetched ${results.length}/${ASSETS.length} price(s) via a consensus-validated on-chain Somnia Agent call — not a plain HTTP request.\n`
  );
}

main().catch((err) => {
  console.error("❌ price-oracle-agent failed:\n", err);
  process.exit(1);
});
